//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dystir.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dystir.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Assist
        {
            get
            {
                return ResourceManager.GetString("Assist", resourceCulture);
            }
        }

        public static string Assists
        {
            get
            {
                return ResourceManager.GetString("Assists", resourceCulture);
            }
        }

        public static string ATT
        {
            get
            {
                return ResourceManager.GetString("ATT", resourceCulture);
            }
        }

        public static string BackButtonText
        {
            get
            {
                return ResourceManager.GetString("BackButtonText", resourceCulture);
            }
        }

        public static string BigChance
        {
            get
            {
                return ResourceManager.GetString("BigChance", resourceCulture);
            }
        }

        public static string BigChanceStatistic
        {
            get
            {
                return ResourceManager.GetString("BigChanceStatistic", resourceCulture);
            }
        }

        public static string BlockedShot
        {
            get
            {
                return ResourceManager.GetString("BlockedShot", resourceCulture);
            }
        }

        public static string BlockedShotStatistic
        {
            get
            {
                return ResourceManager.GetString("BlockedShotStatistic", resourceCulture);
            }
        }

        public static string Commentary
        {
            get
            {
                return ResourceManager.GetString("Commentary", resourceCulture);
            }
        }

        public static string ConnectionLost
        {
            get
            {
                return ResourceManager.GetString("ConnectionLost", resourceCulture);
            }
        }

        public static string Corner
        {
            get
            {
                return ResourceManager.GetString("Corner", resourceCulture);
            }
        }

        public static string CornerStatistic
        {
            get
            {
                return ResourceManager.GetString("CornerStatistic", resourceCulture);
            }
        }

        public static string DEF
        {
            get
            {
                return ResourceManager.GetString("DEF", resourceCulture);
            }
        }

        public static string DrawShort
        {
            get
            {
                return ResourceManager.GetString("DrawShort", resourceCulture);
            }
        }

        public static string ExtraTimeFinished
        {
            get
            {
                return ResourceManager.GetString("ExtraTimeFinished", resourceCulture);
            }
        }

        public static string ExtraTimePause
        {
            get
            {
                return ResourceManager.GetString("ExtraTimePause", resourceCulture);
            }
        }

        public static string Finished
        {
            get
            {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }

        public static string FirstEleven
        {
            get
            {
                return ResourceManager.GetString("FirstEleven", resourceCulture);
            }
        }

        public static string Fixtures
        {
            get
            {
                return ResourceManager.GetString("Fixtures", resourceCulture);
            }
        }

        public static string FullTime
        {
            get
            {
                return ResourceManager.GetString("FullTime", resourceCulture);
            }
        }

        public static string GK
        {
            get
            {
                return ResourceManager.GetString("GK", resourceCulture);
            }
        }

        public static string Goal
        {
            get
            {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }

        public static string GoalsAgainst
        {
            get
            {
                return ResourceManager.GetString("GoalsAgainst", resourceCulture);
            }
        }

        public static string GoalsDiffrent
        {
            get
            {
                return ResourceManager.GetString("GoalsDiffrent", resourceCulture);
            }
        }

        public static string GoalsScored
        {
            get
            {
                return ResourceManager.GetString("GoalsScored", resourceCulture);
            }
        }

        public static string GoalStatistic
        {
            get
            {
                return ResourceManager.GetString("GoalStatistic", resourceCulture);
            }
        }

        public static string HalfTime
        {
            get
            {
                return ResourceManager.GetString("HalfTime", resourceCulture);
            }
        }

        public static string LosesShort
        {
            get
            {
                return ResourceManager.GetString("LosesShort", resourceCulture);
            }
        }

        public static string Matches
        {
            get
            {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }

        public static string MatchPlayedShort
        {
            get
            {
                return ResourceManager.GetString("MatchPlayedShort", resourceCulture);
            }
        }

        public static string MID
        {
            get
            {
                return ResourceManager.GetString("MID", resourceCulture);
            }
        }

        public static string NoMatches
        {
            get
            {
                return ResourceManager.GetString("NoMatches", resourceCulture);
            }
        }

        public static string OffTarget
        {
            get
            {
                return ResourceManager.GetString("OffTarget", resourceCulture);
            }
        }

        public static string OffTargetStatistic
        {
            get
            {
                return ResourceManager.GetString("OffTargetStatistic", resourceCulture);
            }
        }

        public static string OnTarget
        {
            get
            {
                return ResourceManager.GetString("OnTarget", resourceCulture);
            }
        }

        public static string OnTargetStatistic
        {
            get
            {
                return ResourceManager.GetString("OnTargetStatistic", resourceCulture);
            }
        }

        public static string OwnGoal
        {
            get
            {
                return ResourceManager.GetString("OwnGoal", resourceCulture);
            }
        }

        public static string Penalties
        {
            get
            {
                return ResourceManager.GetString("Penalties", resourceCulture);
            }
        }

        public static string Penalty
        {
            get
            {
                return ResourceManager.GetString("Penalty", resourceCulture);
            }
        }

        public static string PenaltyMissed
        {
            get
            {
                return ResourceManager.GetString("PenaltyMissed", resourceCulture);
            }
        }

        public static string PenaltyScored
        {
            get
            {
                return ResourceManager.GetString("PenaltyScored", resourceCulture);
            }
        }

        public static string Points
        {
            get
            {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }

        public static string RedCardStatistic
        {
            get
            {
                return ResourceManager.GetString("RedCardStatistic", resourceCulture);
            }
        }

        public static string Results
        {
            get
            {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }

        public static string SeeMore
        {
            get
            {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }

        public static string Standings
        {
            get
            {
                return ResourceManager.GetString("Standings", resourceCulture);
            }
        }

        public static string Statistics
        {
            get
            {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }

        public static string StatisticsTab
        {
            get
            {
                return ResourceManager.GetString("StatisticsTab", resourceCulture);
            }
        }

        public static string Substitution
        {
            get
            {
                return ResourceManager.GetString("Substitution", resourceCulture);
            }
        }

        public static string Summary
        {
            get
            {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }

        public static string Team
        {
            get
            {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }

        public static string Today
        {
            get
            {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }

        public static string TopScorers
        {
            get
            {
                return ResourceManager.GetString("TopScorers", resourceCulture);
            }
        }

        public static string VictoriesShort
        {
            get
            {
                return ResourceManager.GetString("VictoriesShort", resourceCulture);
            }
        }

        public static string YellowCardStatistic
        {
            get
            {
                return ResourceManager.GetString("YellowCardStatistic", resourceCulture);
            }
        }

        public static string HoursShort
        {
            get
            {
                return ResourceManager.GetString("HoursShort", resourceCulture);
            }
        }
    }
}
