//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DystirManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourcesFO {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesFO() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DystirManager.Properties.", typeof(ResourcesFO).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hendingar.
        /// </summary>
        internal static string Commentary {
            get {
                return ResourceManager.GetString("Commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fyrstu 11.
        /// </summary>
        internal static string FirstEleven {
            get {
                return ResourceManager.GetString("FirstEleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komandi DystirManager.
        /// </summary>
        internal static string Fixtures {
            get {
                return ResourceManager.GetString("Fixtures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DystirManager.
        /// </summary>
        internal static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úrslit.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Støðan.
        /// </summary>
        internal static string Standings {
            get {
                return ResourceManager.GetString("Standings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hagtøl.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyka.
        /// </summary>
        internal static string Substitution {
            get {
                return ResourceManager.GetString("Substitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úrtak.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Í dag.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string ConnectionLost
        {
            get
            {
                return ResourceManager.GetString("ConnectionLost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Goal
        {
            get
            {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BackButtonText.
        /// </summary>
        internal static string BackButtonText
        {
            get
            {
                return ResourceManager.GetString("BackButtonText", resourceCulture);
            }
        }
    }
}
