//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DystirManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DystirManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commentary.
        /// </summary>
        internal static string Commentary {
            get {
                return ResourceManager.GetString("Commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First 11.
        /// </summary>
        internal static string FirstEleven {
            get {
                return ResourceManager.GetString("FirstEleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixtures.
        /// </summary>
        internal static string Fixtures {
            get {
                return ResourceManager.GetString("Fixtures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matches.
        /// </summary>
        internal static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standings.
        /// </summary>
        internal static string Standings {
            get {
                return ResourceManager.GetString("Standings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Substitution.
        /// </summary>
        internal static string Substitution {
            get {
                return ResourceManager.GetString("Substitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string ConnectionLost
        {
            get
            {
                return ResourceManager.GetString("ConnectionLost", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Goal
        {
            get
            {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string OwnGoal
        {
            get
            {
                return ResourceManager.GetString("OwnGoal", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string PenaltyScored
        {
            get
            {
                return ResourceManager.GetString("PenaltyScored", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string BigChance
        {
            get
            {
                return ResourceManager.GetString("BigChance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Penalty
        {
            get
            {
                return ResourceManager.GetString("Penalty", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string PenaltyMissed
        {
            get
            {
                return ResourceManager.GetString("PenaltyMissed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Corner
        {
            get
            {
                return ResourceManager.GetString("Corner", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string OnTarget
        {
            get
            {
                return ResourceManager.GetString("OnTarget", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string OffTarget
        {
            get
            {
                return ResourceManager.GetString("OffTarget", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        internal static string Assist
        {
            get
            {
                return ResourceManager.GetString("Assist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Team.
        /// </summary>
        internal static string Team
        {
            get
            {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GK.
        /// </summary>
        internal static string GK
        {
            get
            {
                return ResourceManager.GetString("GK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to DEF.
        /// </summary>
        internal static string DEF
        {
            get
            {
                return ResourceManager.GetString("DEF", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MID.
        /// </summary>
        internal static string MID
        {
            get
            {
                return ResourceManager.GetString("MID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ATT.
        /// </summary>
        internal static string ATT
        {
            get
            {
                return ResourceManager.GetString("ATT", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ATT.
        /// </summary>
        internal static string BLOCKEDSHOT
        {
            get
            {
                return ResourceManager.GetString("BlockedShot", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ATT.
        /// </summary>
        internal static string NoMatches
        {
            get
            {
                return ResourceManager.GetString("NoMatches", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BackButtonText.
        /// </summary>
        internal static string BackButtonText
        {
            get
            {
                return ResourceManager.GetString("BackButtonText", resourceCulture);
            }
        }
            
        internal static string SeeMore
        {
            get
            {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }

        internal static string HalfTime
        {
            get
            {
                return ResourceManager.GetString("HalfTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FullTime.
        /// </summary>
        internal static string FullTime
        {
            get
            {
                return ResourceManager.GetString("FullTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string Finished
        {
            get
            {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }

        internal static string ExtraTimePause
        {
            get
            {
                return ResourceManager.GetString("ExtraTimePause", resourceCulture);
            }
        }

        internal static string ExtraTimeFinished
        {
            get
            {
                return ResourceManager.GetString("ExtraTimeFinished", resourceCulture);
            }
        }

        internal static string Penalties
        {
            get
            {
                return ResourceManager.GetString("Penalties", resourceCulture);
            }
        }

        internal static string BigChanceStatistic
        {
            get
            {
                return ResourceManager.GetString("BigChanceStatistic", resourceCulture);
            }
        }

        internal static string BlockedShotStatistic
        {
            get
            {
                return ResourceManager.GetString("BlockedShotStatistic", resourceCulture);
            }
        }

        internal static string CornerStatistic
        {
            get
            {
                return ResourceManager.GetString("CornerStatistic", resourceCulture);
            }
        }

        internal static string GoalStatistic
        {
            get
            {
                return ResourceManager.GetString("GoalStatistic", resourceCulture);
            }
        }

        internal static string OffTargetStatistic
        {
            get
            {
                return ResourceManager.GetString("OffTargetStatistic", resourceCulture);
            }
        }

        internal static string OnTargetStatistic
        {
            get
            {
                return ResourceManager.GetString("OnTargetStatistic", resourceCulture);
            }
        }

        internal static string RedCardStatistic
        {
            get
            {
                return ResourceManager.GetString("RedCardStatistic", resourceCulture);
            }
        }

        internal static string YellowCardStatistic
        {
            get
            {
                return ResourceManager.GetString("YellowCardStatistic", resourceCulture);
            }
        }

    }
}
