//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dystir.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_fo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_fo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dystir.Resources.Localization.Resources.fo", typeof(Resources_fo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upplegg.
        /// </summary>
        internal static string Assist {
            get {
                return ResourceManager.GetString("Assist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upplegg.
        /// </summary>
        internal static string Assists {
            get {
                return ResourceManager.GetString("Assists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AL.
        /// </summary>
        internal static string ATT {
            get {
                return ResourceManager.GetString("ATT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ❮ Aftur.
        /// </summary>
        internal static string BackButtonText {
            get {
                return ResourceManager.GetString("BackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stórur møguleiki.
        /// </summary>
        internal static string BigChance {
            get {
                return ResourceManager.GetString("BigChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STÓRUR MØGULEIKI.
        /// </summary>
        internal static string BigChanceStatistic {
            get {
                return ResourceManager.GetString("BigChanceStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blokera skot.
        /// </summary>
        internal static string BlockedShot {
            get {
                return ResourceManager.GetString("BlockedShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLOKERA SKOT.
        /// </summary>
        internal static string BlockedShotStatistic {
            get {
                return ResourceManager.GetString("BlockedShotStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hendingar.
        /// </summary>
        internal static string Commentary {
            get {
                return ResourceManager.GetString("Commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einki samband.
        /// </summary>
        internal static string ConnectionLost {
            get {
                return ResourceManager.GetString("ConnectionLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hornaspark.
        /// </summary>
        internal static string Corner {
            get {
                return ResourceManager.GetString("Corner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HORNA.
        /// </summary>
        internal static string CornerStatistic {
            get {
                return ResourceManager.GetString("CornerStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VL.
        /// </summary>
        internal static string DEF {
            get {
                return ResourceManager.GetString("DEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JD.
        /// </summary>
        internal static string DrawShort {
            get {
                return ResourceManager.GetString("DrawShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to longd leiktíð liðugt.
        /// </summary>
        internal static string ExtraTimeFinished {
            get {
                return ResourceManager.GetString("ExtraTimeFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to longd leiktíð hálvleikur.
        /// </summary>
        internal static string ExtraTimePause {
            get {
                return ResourceManager.GetString("ExtraTimePause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liðugt.
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fyrstu 11.
        /// </summary>
        internal static string FirstEleven {
            get {
                return ResourceManager.GetString("FirstEleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KOMANDI.
        /// </summary>
        internal static string Fixtures {
            get {
                return ResourceManager.GetString("Fixtures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fríggjadagur.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liðugt.
        /// </summary>
        internal static string FullTime {
            get {
                return ResourceManager.GetString("FullTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM.
        /// </summary>
        internal static string GK {
            get {
                return ResourceManager.GetString("GK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mál.
        /// </summary>
        internal static string Goal {
            get {
                return ResourceManager.GetString("Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MÍ.
        /// </summary>
        internal static string GoalsAgainst {
            get {
                return ResourceManager.GetString("GoalsAgainst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM.
        /// </summary>
        internal static string GoalsDiffrent {
            get {
                return ResourceManager.GetString("GoalsDiffrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MF.
        /// </summary>
        internal static string GoalsScored {
            get {
                return ResourceManager.GetString("GoalsScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MÁL.
        /// </summary>
        internal static string GoalStatistic {
            get {
                return ResourceManager.GetString("GoalStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hálvleikur.
        /// </summary>
        internal static string HalfTime {
            get {
                return ResourceManager.GetString("HalfTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to t..
        /// </summary>
        internal static string HoursShort {
            get {
                return ResourceManager.GetString("HoursShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TD.
        /// </summary>
        internal static string LosesShort {
            get {
                return ResourceManager.GetString("LosesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DYSTIR.
        /// </summary>
        internal static string Matches {
            get {
                return ResourceManager.GetString("Matches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DS.
        /// </summary>
        internal static string MatchPlayedShort {
            get {
                return ResourceManager.GetString("MatchPlayedShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MV.
        /// </summary>
        internal static string MID {
            get {
                return ResourceManager.GetString("MID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mánadagur.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingin dystur.
        /// </summary>
        internal static string NoMatches {
            get {
                return ResourceManager.GetString("NoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roynd frammvið mál.
        /// </summary>
        internal static string OffTarget {
            get {
                return ResourceManager.GetString("OffTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROYNDIR FRAMMVIÐ MÁL.
        /// </summary>
        internal static string OffTargetStatistic {
            get {
                return ResourceManager.GetString("OffTargetStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roynd á mál.
        /// </summary>
        internal static string OnTarget {
            get {
                return ResourceManager.GetString("OnTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ROYNDIR Á MÁL.
        /// </summary>
        internal static string OnTargetStatistic {
            get {
                return ResourceManager.GetString("OnTargetStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sjálvmál.
        /// </summary>
        internal static string OwnGoal {
            get {
                return ResourceManager.GetString("OwnGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brotsspark.
        /// </summary>
        internal static string Penalties {
            get {
                return ResourceManager.GetString("Penalties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brotsspark.
        /// </summary>
        internal static string Penalty {
            get {
                return ResourceManager.GetString("Penalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brotsspark brent.
        /// </summary>
        internal static string PenaltyMissed {
            get {
                return ResourceManager.GetString("PenaltyMissed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brotsspark skora.
        /// </summary>
        internal static string PenaltyScored {
            get {
                return ResourceManager.GetString("PenaltyScored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dagsins leikari.
        /// </summary>
        internal static string PlayerOfTheMatch {
            get {
                return ResourceManager.GetString("PlayerOfTheMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to St..
        /// </summary>
        internal static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REYÐ KORT.
        /// </summary>
        internal static string RedCardStatistic {
            get {
                return ResourceManager.GetString("RedCardStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÚRSLIT.
        /// </summary>
        internal static string Results {
            get {
                return ResourceManager.GetString("Results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leygardagur.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vís meira ❯.
        /// </summary>
        internal static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STØÐAN.
        /// </summary>
        internal static string Standings {
            get {
                return ResourceManager.GetString("Standings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Støðan.
        /// </summary>
        internal static string StandingsTab {
            get {
                return ResourceManager.GetString("StandingsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hagtøl.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HAGTØL.
        /// </summary>
        internal static string StatisticsTab {
            get {
                return ResourceManager.GetString("StatisticsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eyka.
        /// </summary>
        internal static string Substitution {
            get {
                return ResourceManager.GetString("Substitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úrtak.
        /// </summary>
        internal static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunnudagur.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIÐ.
        /// </summary>
        internal static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hósdagur.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Í dag.
        /// </summary>
        internal static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Málskjúttar.
        /// </summary>
        internal static string TopScorers {
            get {
                return ResourceManager.GetString("TopScorers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Týsdagur.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VD.
        /// </summary>
        internal static string VictoriesShort {
            get {
                return ResourceManager.GetString("VictoriesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mikudagur.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GUL KORT.
        /// </summary>
        internal static string YellowCardStatistic {
            get {
                return ResourceManager.GetString("YellowCardStatistic", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string Days
        {
            get
            {
                return ResourceManager.GetString("Days", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string Players
        {
            get
            {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
    }
}
